StanfordBDHG/HealthKitOnFHIR

Sources/HealthKitOnFHIR/HKQuantitySample/HKCumulativeQuantitySample/HKCumulativeQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKSample+Observation.swift
Sources/HealthKitOnFHIR/HealthKitOnFHIRError.swift
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift
Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme

This PR creates a first draft of the HealthKitOnFHIR API surface. Developers can transform any `HKSample` to a FHIR `Observation` using the `observation` computed property that can throw an `HealthKitOnFHIRError` of the conversion fails:
```swift
let cumulativeQuantitySample = HKCumulativeQuantitySample(
type: HKQuantityType(.stepCount),
quantity: HKQuantity(unit: .count(), doubleValue: 42),
start: startDate,
end: endDate
)
let observation = try cumulativeQuantitySample.observation // Functionality provided by HealthKitOnFHIR
```

Create HealthKitOnFHIR API

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKCumulativeQuantitySample/HKCumulativeQuantitySample+Observation.swift
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

In this PR, we add and test the first conversion from an HKQuantityType to a FHIR observation, including mapping to a LOINC code and category code.

Convert HKQuantityTypeIdentifierStepCount to FHIR Observation

---

Package.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKCumulativeQuantitySample/HKCumulativeQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKTypeCodeSystemMapper.swift
Sources/HealthKitOnFHIR/mapping.json
Sources/HealthKitOnFHIR/mapping.json.license
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Creates an extension that maps between HKQuantityTypes and corresponding codes in standardized Code Systems (e.g. LOINC, SNOMED CT). Mappings are configured via `mapping.json`.

Create HKQuantityType to Code System Mapper

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKCumulativeQuantitySample/HKCumulativeQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/mapping.json
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Adds ability to convert [HKQuantityTypeIdentifierOxygenSaturation](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifieroxygensaturation) values to FHIR observations.

Adds conversion for Oxygen Saturation

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKCumulativeQuantitySample/HKCumulativeQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/mapping.json
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Adds support for converting [HKQuantityTypeIdentifierBodyTemperature](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifierbodytemperature) data to FHIR Observations.

Adds conversion for Body Temperature

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/mapping.json
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Adds support for converting [HKQuantityTypeIdentifierHeight](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/1615039-height) data to FHIR Observations.

Adds conversion for Height

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/mapping.json
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Adds support for converting HKQuantityTypeIdentifierBodyMass data to FHIR Observations.

Adds conversion for Body Mass

---

Sources/HealthKitOnFHIR/HKQuantitySample/HKDiscreteQuantitySample/HKDiscreteQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/mapping.json
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Adds support for converting [HKQuantityTypeIdentifierRespiratoryRate](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/1615094-respiratoryrate) data to FHIR Observations.

Adds conversion for Respiratory Rate

---

Sources/HealthKitOnFHIR/HKSampleMapping/MappedUnit.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/CustomMappingsTests.swift
Tests/HealthKitOnFHIRTests/HealthKitOnFHIRTests.swift

Units need to be mapped to a standardized code system, such as [UCUM](http://unitsofmeasure.org).
This PR updates the HealthKit type mapping to use UCUM units when generating the valueQuantity element in a FHIR observation. Other unit code systems can be used by editing the `mapping.json` file in the `Resources` folder.

Map units to standardized UCUM codes

---

LICENSE.md
Sources/HealthKitOnFHIR/HKSample+Observation.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKCorrelationMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKQuantitySampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKSampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/MappedCode.swift
Sources/HealthKitOnFHIR/HKSampleMapping/MappedUnit.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantityType+Coding.swift
Sources/HealthKitOnFHIR/Observation Extensions/Observation+Collections.swift
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/CustomMappingsTests.swift

The current API uses string values for `HKQuantityType`s, `HKCorrelationType`s, and `HKUnit`s. These interfaces use runtime errors such as `fatalError` to validate the correct values of these String values. 
In addition, before we tag a first release we should have an inline code documentation in place.
The PR adds type-safe interfaces to the APIs, reducing the amount of runtime checking and simplifying the Swift-based interface. Runtime checks are still required for decoding elements from the JSON representation. Making the properties of the configuration types mutable reduces the need to parse a JSON file and allow users to extend the functionality in a Swift-based interface without the need to copy the JSON file from the repository.
This PR also adds inline code documentation for the …

Make the API More Type-Safe and Add API Documentation 

---

.github/workflows/build-docs.yml

The 'build-docs' workflow is not running due to a path error, this PR fixes it.

Fix for path error in build-docs action

---

Scripts/support_table_generator.py
Sources/HealthKitOnFHIR/HKSampleMapping/HKElectrocardiogramMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKSampleMapping.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategorySample+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKElectrocardiogram+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+Observation.swift
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/HKElectrocardiogramTests.swift
Tests/UITests/TestApp/HKElectrocardiogram+Context.swift
Tests/UITests/TestApp/HealthKitManager.swift
Tests/UITests/TestApp/Views/ContentView.swift
Tests/UITests/TestApp/Views/ElectrocardiogramTestView.swift
Tests/UITests/TestApp/Views/JSONView.swift
Tests/UITests/TestApp/Views/ReadDataView.swift
Tests/UITests/TestApp/Views/WriteDataView.swift
Tests/UITests/TestAppUITests/TestAppUITests.swift
Tests/UITests/TestAppUITests/XCTTestCase+HealthDataType.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

`HKElectrocardiogram` is a commonly used HealthKit sample type that is collected using an Apple Watch or other ECG devices. 
Adds an mapping of an ecg to an FHIR observation.
The observation uses this format as displayed in the example below.
The `component` section includes the Apple provided `HKElectrocardiogram.NumberOfVoltageMeasurements`, `HKElectrocardiogram.SamplingFrequency`, and `HKElectrocardiogram.Classification` metadata associated with an ECG.
The `component` section also includes multiple `HKCategoryType` encoded values representing the symptoms if they are passed in the `observation(symptoms: Symptoms, voltageMeasurements: VoltageMeasurements, withMapping mapping: HKSampleMapping)` function.
The `component` section also includes multiple `valueSampledData` raw voltage …

Add HKElectrocardiogram to Observation Mapping

---

CITATION.cff
README.md

The ResearchKitOnFHIR can currently only be references using its URL.
This PR adds the necessary infrastructure and connections to properly reference the software. It adds a citation File and DOI to Reference HealthKitOnFHIR in Publications.

Add Citation File and DOI to Reference HealthKitOnFHIR in Publications

---

Sources/HealthKitOnFHIR/HealthKit Extensions/HKSampleType+ResourceType.swift
Tests/HealthKitOnFHIRTests/HKSampleTypeResourceTypeMapping.swift

While the HKSample extensions provide a reasonable mapping of concrete HKSamples, some mapping functionality needs to determine the corresponding resource type for an abstract HKSampleType.
This PR adds a small extension to `HKSampleType` to determine a best-effort approach of mapping an `HKSampleType` to an `ResourceType`.

Add HKSampleType to ResourceType

---

Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Tests/UITests/TestAppUITests/TestAppUITests.swift

The current conversion to a FHIR resource doesn't set its id property. We assign this ID property internally to the HKSample id. It can be overwritten or adapted if the FHIR resources should be uploaded to a FHIR server.

Assign ID Property

---

Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/UITests/TestApp/Views/ElectrocardiogramTestView.swift
Tests/UITests/TestAppUITests/TestAppUITests.swift

The ECG observation has an incorrect coding.
Fixes the ECG coding to match the example given in the FHIR R4 documentation (see: http://hl7.org/fhir/observation-example-sample-data.html)

Fixes ECG coding

---

.github/workflows/build-and-test.yml
.github/workflows/pull_request.yml
Sources/HealthKitOnFHIR/HKSampleMapping/HKCategorySampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKCorrelationMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKQuantitySampleMapping.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKElectrocardiogram+Observation.swift

- The current batch calculation of the ECG currently omits half of the recorded voltage measurements due to a bug that discarded the second half of the 10 second intervals.
- This PR moves away from the split method + remainder calculation and inserts an assertion to check that the batches contain the same amount of values as the initial recoding.
The functionality is tested using the UI test and the included assertion.

Fix ECG Batch Calculation

---

.github/workflows/build-and-test.yml
Scripts/support_table_generator.py
Sources/HealthKitOnFHIR/HealthKitOnFHIR.docc/HKSampleSupportTables.md
Sources/HealthKitOnFHIR/HealthKitOnFHIR.docc/SupportedHKQuantityTypes.md
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/HKQuantitySampleTests.swift

Two gait metrics present in HealthKit are not currently supported by HealthKitOnFHIR:
- [Walking Asymmetry Percentage](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/3552086-walkingasymmetrypercentage)
- [Apple Walking Steadiness](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/3747016-applewalkingsteadiness)
Adds support for the above HK quantity types.
Updates the documentation to reflect the new types.
Adds a test for each new type.

Adds support for additional gait metrics

---

.github/workflows/build-and-test.yml
Package.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKCategorySampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKCorrelationMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKElectrocardiogramMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKQuantitySampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKSampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKWorkoutSampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/MappedCode.swift
Sources/HealthKitOnFHIR/HKSampleMapping/MappedUnit.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKElectrocardiogram+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKitOnFHIRError.swift
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/UITests/TestAppUITests/TestAppUITests.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

- ECG voltage values are currently mapped to a string representation discarding their precision and reasonable number of decimal values.
- Improve ECG Mapping With a Precision Setting

Improve ECG Mapping With a Precision Setting

---

Package.swift
Tests/UITests/TestAppUITests/TestAppUITests.swift

The Package manifest was missing adding swiftlint as a package dependency. This resulted in failing to load the package if one enabled the `SPEZI_DEVELOPMENT_SWIFTLINT` environment variable.
* Fixed missing swiftlint package dependency.
--
--

Fixed missing swiftlint package dependency

---

Scripts/support_table_generator.py
Sources/HealthKitOnFHIR/HealthKitOnFHIR.docc/HKSampleSupportTables.md
Sources/HealthKitOnFHIR/HealthKitOnFHIR.docc/SupportedHKQuantityTypes.md
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/HKQuantitySampleTests.swift

Since iOS 17, HealthKit has added a [Time in Daylight quantity type](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/4168154-timeindaylight).
Adds a mapping for Time in Daylight to a FHIR Observation.
Documentation script is updated and new documentation has been generated.
Unit test added.

Add mapping for Time In Daylight

---

README.md
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+TimeZone.swift
Sources/HealthKitOnFHIR/Observation Extensions/Observation+Dates.swift
Tests/HealthKitOnFHIRTests/TimeZoneTests.swift

The HealthKitOnFHIR library currently assumes that HealthKit samples were created in the current time zone of the device at the time of mapping and applies the corresponding UTC offset. While this is true for most situations, it is possible that older HealthKit data may be mapped using the library that was created while the user was in a different time zone. 
For example, if a sample was originally created by HealthKit in San Francisco on December 1st, 2024 at 9:00am (-08:00), but then mapped by HealthKitOnFHIR later on in New York, the timestamp would read 2024-12-01T12:00:00-05:00. While technically these are the same point in time, they are offset differently.
The information regarding the original timezone of the sample may be stored by HealthKit in the object's metadata via …

Set time zone from HK metadata in FHIR resources

---

.github/workflows/build-and-test.yml
Package.swift
Sources/HealthKitOnFHIR/HKSampleMapping/HKSampleMapping.swift
Sources/HealthKitOnFHIR/HKSampleMapping/MappedUnit.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategoryValue+String.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKClinicalRecord+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKElectrocardiogram+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKWorkoutActivityType+String.swift
Tests/HealthKitOnFHIRTests/HKQuantitySampleTests.swift
Tests/HealthKitOnFHIRTests/TimeZoneTests.swift
Tests/UITests/TestApp/HealthKitManager.swift
Tests/UITests/TestApp/Views/CreateWorkoutView.swift
Tests/UITests/TestApp/Views/ElectrocardiogramTestView.swift
Tests/UITests/TestApp/Views/HealthRecordsTestView.swift
Tests/UITests/TestApp/Views/ReadDataView.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

- This PR adds explicit support for watchOS targets, with some new conditional availability handling for `HKClinicalRecord`, which isn't available on watchOS.
- This PR also updates the swift-tools-version to 6.0, and makes some corresponding changes (a bunch of protocol conformance extensions are now marked as `@retroactive`, to make explicit what previously was implicit behavior)
- The UITests application is also migrated to Swift 6
- The PR also adds the `ExistentialAny` swift flag.
Additionally, this PR fixes an issue with the time zone-related tests, which is probably only occurring right now since the US is currently in DST, while the UK (ie, GMT) hasn't yet switched over.
- added support for watchOS and macOS
- updated to Swift 6
n/a
n/a
By creating and submitting this pull …

explicit watchOS support, Swift 6, existential any

---

CONTRIBUTORS.md
README.md
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKitOnFHIR.docc/HealthKitOnFHIR.md
Sources/HealthKitOnFHIR/Observation Extensions/Observation+Dates.swift
Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
Tests/HealthKitOnFHIRTests/HKCorrelationTests.swift
Tests/HealthKitOnFHIRTests/HKQuantitySampleTests.swift
Tests/HealthKitOnFHIRTests/HKWorkoutTests.swift
Tests/HealthKitOnFHIRTests/TimeZoneTests.swift
Tests/UITests/TestApp/TestApp.swift
Tests/UITests/TestApp/Views/ContentView.swift
Tests/UITests/TestApp/Views/ExportDataView.swift
Tests/UITests/TestApp/Views/HealthRecordsTestView.swift
Tests/UITests/TestApp/Views/ReadDataView.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

HealthKitOnFHIR defines a `HKSample` extension to create a `ResourceProxy` for a sample.
Parts of this process are currently very slow, namely the date handling when creating the `Observation`.
When operating only on a small number of samples, this isn't really noticable, but for larger amounts of samples it does start to add up.
There are 2 performance bottlenecks:
1. Use of `DateFormatter`s when creating the `FHIRPrimitive<DateTime>` objects
- sub-issue: the `DateFormatter`s currently are re-created every time the `resource()` function is called — creating `DateFormatter` instances is very expensive!
- using a `DateFormatter` here is also not really necessary; the code currently turns a `Date` into a `String`, and then passes that to FHIR's `DateTime` init to parse it back into a date. …

vastly improve HKSample → ResourceProxy performance

---

Sources/HealthKitOnFHIR/HealthKit Extensions/FHIRObservationBuildable.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategorySample+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategoryValue+String.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKClinicalRecord+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKElectrocardiogram+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantitySample+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantityType+Coding.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKSample+ResourceProxy.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKWorkout+Observation.swift
Sources/HealthKitOnFHIR/HealthKit Extensions/HKWorkoutActivityType+String.swift
Sources/HealthKitOnFHIR/Observation Extensions/Observation+Collections.swift
Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
Tests/HealthKitOnFHIRTests/CustomMappingsTests.swift
Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
Tests/HealthKitOnFHIRTests/HKCorrelationTests.swift
Tests/HealthKitOnFHIRTests/HKElectrocardiogramTests.swift
Tests/HealthKitOnFHIRTests/HKQuantitySampleTests.swift
Tests/HealthKitOnFHIRTests/HKSampleTypeResourceTypeMapping.swift
Tests/HealthKitOnFHIRTests/HKWorkoutTests.swift
Tests/HealthKitOnFHIRTests/ObservationExtensionsTests.swift
Tests/HealthKitOnFHIRTests/TimeZoneTests.swift
Tests/UITests/TestApp/Views/CheckMappingCompletenessView.swift
Tests/UITests/TestApp/Views/ContentView.swift
Tests/UITests/TestApp/Views/CreateWorkoutView.swift
Tests/UITests/TestAppUITests/TestAppUITests.swift
Tests/UITests/UITests.xcodeproj/project.pbxproj

HealthKitOnFHIR currently doesn't support all sample types supported by HealthKit.
This PR adds support for additional category and quantity types, attempting to bring the set of sample types supported by HealthKitOnFHIR in line with what's supported by SpeziHealthKit (which, to the best of my knowledge, should currently support all sample types defined by HealthKit).
The PR also reworks the category sample handling a bit, to reduce code duplication and make it easier to add additional types in the future.
It also improves the FHIR observation creation for `HKCategorySample`s, by also handling the metadata associated with some category types.
Additionally, we remove the `resource` computed property, in preparation for an upcoming 1.0 release.
- added support for more sample types.
n/a; …

more sample types

---

Sources/HealthKitOnFHIR/Observation Extensions/Observation+Collections.swift
Sources/HealthKitOnFHIR/Observation Extensions/Observation+Dates.swift

This PR makes some of the `Observation` extensions defined by HealthKitOnFHIR public, so that they can also be used by other apps/packages to construct `Observation`s
- made some `Observation` extensions public
the now-public functions are documented
n/a
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):

make some observation extensions public
